<a href="https://colab.research.google.com/github/Sanjay0958/Matrix-assignment/blob/main/customer_chunk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
import pickle

In [ ]:
dataset=pd.read_csv('/content/Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
x=dataset.iloc[:,3:-1]
y=dataset.iloc[:,-1].values
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
print(x['Geography'].value_counts())
print(x['Gender'].value_counts())
print(x['NumOfProducts'].value_counts())
print(x['HasCrCard'].value_counts())
print(x['IsActiveMember'].value_counts())

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64
Male      5457
Female    4543
Name: Gender, dtype: int64
1    5084
2    4590
3     266
4      60
Name: NumOfProducts, dtype: int64
1    7055
0    2945
Name: HasCrCard, dtype: int64
1    5151
0    4849
Name: IsActiveMember, dtype: int64


In [ ]:
x.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary  
count  10000.00000    10000.000000     10000.000000  
mean       0.70550        0.515100    100090.239881  
std        0.45584        0.499797     57510.492818  
min        0.00000        0.000000        11.580000  
25%        0.00000        0.000000     51002.110000  
50%        1.00000        1.000000    100193.915000  
75%        1.00000        1.000000    149388.247500  
max        1.00000        1.000000    199992.480000

In [ ]:
#isnull shows all value in true or false sum is for calcluate the count of true
x.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [ ]:
unique, counts=np.unique(y, return_counts=True)

print(np.asarray((unique, counts)))

[[   0    1]
 [7963 2037]]


In [ ]:
#values of number into 0 and 1 using one hand encoding
x=pd.get_dummies(x,drop_first=True)

In [ ]:
#training the dataset
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.1,stratify=y,random_state=1)
print(x_train)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
4493          825   32       1       0.00              2          1   
1306          823   46       3   81576.75              1          1   
7313          687   36       4   97157.96              1          0   
7408          715   35       2  141005.47              1          1   
7402          647   33       7  121260.19              2          1   
...           ...  ...     ...        ...            ...        ...   
5327          850   25       8   69385.17              2          1   
6738          573   35       9  134498.54              2          1   
2900          626   26       8  148610.41              3          0   
3361          602   48       7   76595.08              2          0   
8407          726   28       2       0.00              1          0   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
4493               1         42935.15                  0              

In [ ]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)
print(x_train)

[[ 1.80857957 -0.6581552  -1.38506348 ... -0.57649493  1.73000044
  -1.09665089]
 [ 1.78791117  0.67354372 -0.69423961 ... -0.57649493  1.73000044
  -1.09665089]
 [ 0.38245964 -0.27766979 -0.34882768 ... -0.57649493 -0.57803454
  -1.09665089]
 ...
 [-0.2479267  -1.2288833   1.03282007 ... -0.57649493  1.73000044
  -1.09665089]
 [-0.49594756  0.86378642  0.68740813 ...  1.73462062 -0.57803454
  -1.09665089]
 [ 0.78549354 -1.0386406  -1.03965155 ... -0.57649493 -0.57803454
   0.91186722]]


In [ ]:
rf=RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred=rf.predict(x_test)

In [ ]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[768  28]
 [110  94]]
0.862


In [ ]:
pickle.dump(rf,open('customer_chunk_pred.pkl','wb'))